add option to install of OS packages * moduralize the install script * install vim-plug * run PlugInstall at setup time * run GoInstall Binaries at setup time

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,43 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+if [[ -z "$1" ]] ; then
+  echo "FATAL: args required.  You likely want to run"
+  echo "       $0 apt clean init"
+  exit 1
+fi
 
 set -exo pipefail
 
-if [[ "$1" == "clean" ]] ; then
-  rm -f \
-    ~/.vimrc
-    ~/.gitconfig
-fi
+for args in "$@" ; do
+  case "${args}" in
+    apt)
+      apt-get update
+      apt-get install -y \
+        vim \
+        curl \
+        golang \
+        git \
+        tmate \
+        tmux
+      ;;
+    clean)
+      rm -f \
+        ~/.vimrc \
+        ~/.gitconfig
+      ;;
+    init)
+      curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
+        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+      ln -s $HOME/work/dot-files/vim/vimrc ~/.vimrc
+      ln -s $HOME/work/dot-files/gitconfig ~/.gitconfig
+      vim -E -c PlugInstall -c q -c q
+      vim -E -c GoInstallBinaries -c q -c q
+      ;;
+    *)
+      echo "FATAL:  unknown options"
+      exit 1
+      ;;
+  esac
+done
 
-ln -s $HOME/work/dot-files/vim/vimrc ~/.vimrc
-ln -s $HOME/work/dot-files/gitconfig ~/.gitconfig
+echo "complete"
